import Link from "next/link";
import Article from "@/components/Article";
import CompareTable from "@/components/CompareTable";
import Sources from "@/components/Sources";
import { CONTENT_UPDATED, SRC } from "@/lib/content";
import { pageMetadata } from "@/lib/seo";

const PATH = "/compare/turnitin";
const TITLE = "Turnitin vs Litimus: Which AI Detector Fits You?";
const DESCRIPTION =
  "Turnitin’s AI Writing Report is an institutional tool; Litimus is open to anyone. How the scores, limits and access differ, and what Turnitin itself says.";

export const metadata = pageMetadata({ title: TITLE, description: DESCRIPTION, path: PATH });

export default function CompareTurnitinPage() {
  return (
    <Article
      eyebrow="Compare"
      title="Litimus vs Turnitin"
      lede="Turnitin’s AI Writing Report sits inside a platform many schools and universities already use. Litimus is a standalone tool that anyone can use without an institution. They are not really substitutes, and the numbers they show do not mean the same thing."
      description={DESCRIPTION}
      path={PATH}
      crumbs={[
        { name: "Compare", path: "/compare" },
        { name: "Turnitin", path: PATH },
      ]}
      updated={CONTENT_UPDATED}
      related={[
        {
          href: "/for/teachers",
          title: "AI detection for teachers",
          blurb: "A fair process for using any detector, including the one your school licenses.",
        },
        {
          href: "/guides/falsely-accused-of-ai-writing",
          title: "Falsely accused of using AI?",
          blurb: "What to do if a detector flagged your own work.",
        },
      ]}
    >
      <div className="callout">
        <p>
          <strong>The short version.</strong> If your institution uses Turnitin, its report is the one your
          institution’s process will refer to, and it also covers similarity checking. Litimus is for people outside
          that workflow: a student checking a draft, a teacher without a licence, an editor or a freelancer. It does
          not replace Turnitin and does not try to match it.
        </p>
      </div>

      <h2>Side by side</h2>
      <CompareTable
        caption="Litimus compared with Turnitin"
        aName="Turnitin AI Writing Report"
        bName="Litimus"
        rows={[
          {
            label: "Who can use it",
            a: "Access depends on your institution’s licence and settings. Turnitin’s guidance is written for instructors.",
            b: "Anyone. A free scan needs no account.",
          },
          {
            label: "What the number means",
            a: "The percentage of “qualifying text” (prose sentences in long-form writing) that the system believes may have been generated by AI tools or altered by AI paraphrasing software.",
            b: "A likelihood score for the whole passage, shown as “% AI-likely” and grouped into three bands: 66 and above AI-likely, 34 and below human-likely, and 35 to 65 mixed / unclear.",
          },
          {
            label: "Low scores",
            a: "Scores from 1% to 19% are not shown as a number. The report shows an asterisk, to reduce false positives.",
            b: "Every score is shown. Middle scores are labelled mixed / unclear rather than hidden.",
          },
          {
            label: "Length and files",
            a: "300 to 30,000 words. Accepts .docx, .pdf, .txt and .rtf, up to 100 MB.",
            b: "Scores from 8 words and flags anything under 25 words as too short for a stable read. Free scans cover 2,000 words a day. Paid plans add .docx and .pdf.",
          },
          {
            label: "Languages",
            a: "Detects English, Spanish, Japanese and Arabic. Paraphrase detection works in English only.",
            b: "Tuned for English.",
          },
          {
            label: "Stated false-positive aim",
            a: "Says it targets a false positive rate below 1%, and that a small risk remains.",
            b: "No rate published. The report and the Terms state that a score is a probability, not proof.",
          },
          {
            label: "Plagiarism checking",
            a: "Turnitin is best known for similarity checking. The AI Writing Report is a separate report.",
            b: "None. Litimus does not compare text against sources.",
          },
        ]}
      />

      <h2>The two numbers are not the same thing</h2>
      <p>
        A Turnitin score of 40% describes how much of the qualifying text the system flagged. A Litimus score of 40
        describes how likely the whole passage is to be machine-written, and it falls in the mixed / unclear band. The
        two answer different questions, so do not read one as a translation of the other, and do not average them.
      </p>

      <h2>Where Turnitin is the better choice</h2>
      <ul>
        <li>
          <strong>Your institution already uses it.</strong> Its report lives in the submission workflow and its status
          under your institution’s policy is defined. Nothing outside that workflow carries the same standing.
        </li>
        <li>
          <strong>You need more than English.</strong> Turnitin lists detection in English, Spanish, Japanese and
          Arabic.
        </li>
        <li>
          <strong>You need similarity checking too.</strong> Litimus does not check for plagiarism.
        </li>
      </ul>

      <h2>Where Litimus is the better choice</h2>
      <ul>
        <li>
          <strong>You are outside an institution, or your institution does not give you access.</strong> A student
          cannot always run a draft through the same report their instructor will see, and Litimus lets you check
          your own writing before you hand it in.
        </li>
        <li>
          <strong>You want the reasoning laid out.</strong> The report shows readings for sentence rhythm, vocabulary
          spread, stock phrases and repeated phrases, and quotes the phrases it found.
        </li>
        <li>
          <strong>You want a second opinion, not a replacement.</strong> If a score surprises you, looking at the
          same text in a different tool can add context. It is never proof either way.
        </li>
      </ul>

      <h2>What Turnitin itself says about its scores</h2>
      <p>
        Turnitin’s guidance says AI writing detection “may not always be accurate” and should not be used as the sole
        basis for adverse action against a student. Its own article on false positives advises educators to assume
        positive intent and to talk with the student about the findings. Litimus’s{" "}
        <Link href="/terms">Terms of Service</Link> ask the same of you. If you are on the receiving end of a score,
        read <Link href="/guides/falsely-accused-of-ai-writing">what to do if you are falsely accused</Link>.
      </p>

      <Sources
        items={[SRC.turnitinGuide, SRC.turnitinFalsePositives]}
        note="Facts about Turnitin come from its published guidance as we read it on the date above. Institutions can configure it differently, so check with yours."
      />
    </Article>
  );
}
