# Litimus — Terms of Service

*Last updated: 24 September 2026.

These Terms of Service ("Terms") govern your access to and use of litimus.app and any related applications or APIs (together, the "Service"), operated by Forsta Group (Pty) Ltd ("Litimus", "we", "us", "our"), a business based in South Africa. By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.

## 1. Description of Service

Litimus provides AI-generated text detection. Users may submit text (by pasting it or uploading a .txt, .docx, or .pdf file) and receive an automated probability score estimating the likelihood that the text was generated by an AI language model. The Service is offered on a free tier (subject to daily usage limits) and on paid subscription tiers (Student, Pro, and Team & API) as well as a once-off Day Pass, as described on our Pricing page.

## 2. Important Disclaimer About Detection Accuracy

**AI-detection results are probabilistic estimates, not proof.** No AI-detection tool, including Litimus, can determine with certainty whether text was written by a human or generated by AI. Results may include false positives (human-written text flagged as AI-generated) and false negatives (AI-generated text not flagged). You agree that:

- You will not treat a Litimus score as conclusive or sole evidence of academic dishonesty, plagiarism, contract fraud, or any other misconduct in any academic, employment, legal, or disciplinary proceeding.
- Any decision made based on a Litimus score (e.g., an academic integrity finding) is made solely at your own discretion and risk, and Litimus accepts no liability for such decisions or their consequences.
- You are responsible for independently verifying any result before relying on it or acting against a third party on the basis of it.

## 3. Eligibility and Accounts

You must be able to form a legally binding contract to use the Service. If you are under the age of majority in your jurisdiction, you may only use the Service with the involvement of a parent or legal guardian. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.

## 4. Free Tier and Fair Use

Free, unregistered use of the Service is limited (currently 2,000 words per rolling day, enforced per visitor). Text submitted through the free anonymous detector is processed locally in your browser; only a word count, not your text, is sent to our servers to enforce this limit. We reserve the right to change free-tier limits at any time. Automated, bulk, or abusive use of the free tier to circumvent paid plan limits is prohibited.

## 5. Subscriptions, Billing, and Payment

- Paid plans are billed on a recurring monthly basis in advance through our payment processor, PayFast.
- By subscribing, you authorise us (via PayFast) to charge your chosen payment method automatically each billing period until you cancel.
- Prices are as displayed on our Pricing page at the time of purchase and may change with notice for future billing periods.
- Refunds and cancellations are governed by our separate Refund Policy.
- You are responsible for providing accurate billing information and for any taxes applicable to your purchase.

## 6. Student Plan

The discounted Student plan is available only to users who can verify current student status through our nominated verification provider. Misrepresenting your eligibility may result in suspension or cancellation of your subscription.

## 7. API and Team Access

Team & API subscribers may access the Service programmatically subject to the rate limits and usage terms of their plan. You may not resell, sublicense, or provide access to the API to third parties outside your own organisation without our prior written consent, and you remain responsible for all use of the Service under your API credentials.

## 8. Acceptable Use

You agree not to:

- Use the Service for any unlawful purpose, or to facilitate harassment, discrimination, or harm against any individual;
- Attempt to reverse-engineer, scrape, or extract the underlying detection methodology or models;
- Circumvent, disable, or interfere with usage limits, rate limits, or security features of the Service;
- Submit content you do not have the legal right to submit, or that infringes the intellectual property or privacy rights of others;
- Use automated means to access the Service outside of the documented API.

We reserve the right to suspend or terminate accounts that violate this section.

## 9. Intellectual Property

The Service, including its software, detection methodology, design, and branding, is owned by Litimus and protected by applicable intellectual property laws. We do not claim ownership of the text you submit for analysis. You retain all rights to content you submit.

## 10. Third-Party Services

The Service relies on third-party infrastructure providers, including but not limited to Supabase (database/authentication), Netlify (hosting), and PayFast (payment processing). Your use of payment features is also subject to PayFast's own terms and privacy policy.

## 11. Privacy

Our collection and use of personal information is described in our [Privacy Policy] (linked separately), which forms part of these Terms.

## 12. Disclaimer of Warranties

The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that detection results will be accurate.

## 13. Limitation of Liability

To the maximum extent permitted by law, Litimus and its officers, employees, and affiliates will not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, goodwill, or reputation, arising from or related to your use of the Service, including reliance on any detection result. Our total aggregate liability for any claim arising from these Terms or the Service will not exceed the amount you paid us in the three (3) months preceding the claim.

Nothing in these Terms limits liability that cannot lawfully be excluded under South African law, including under the Consumer Protection Act 68 of 2008.

## 14. Indemnification

You agree to indemnify and hold Litimus harmless from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these Terms, or any decision or action you take based on a detection result.

## 15. Termination

We may suspend or terminate your access to the Service at any time for violation of these Terms. You may stop using the Service and cancel your subscription at any time via your account dashboard.

## 16. Changes to These Terms

We may update these Terms from time to time. Material changes will be notified via the Service or by email. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.

## 17. Governing Law and Jurisdiction

These Terms are governed by the laws of South Africa. Any disputes will be subject to the exclusive jurisdiction of the South African courts, without prejudice to any mandatory consumer protections available to you in your own jurisdiction.

## 18. Contact

Questions about these Terms can be sent to support@litimus.app / Forsta Group (Pty) Ltd, [insert registered address].

---
*This document is a draft template only and has not been reviewed by a lawyer. Given that Litimus makes probabilistic claims about third-party content (with real reputational/academic consequences for end users) and processes payments and personal data, please have this reviewed by a South African attorney — particularly the accuracy disclaimer, limitation of liability, and POPIA (Protection of Personal Information Act) compliance for the data/privacy sections — before publishing it live.*
